name: almtokenizer
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - atk-1.0=2.36.0
  - boost-cpp=1.82.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cairo=1.16.0
  - comm=0.2.2
  - cpp-expected=1.1.0
  - debugpy=1.8.13
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.7.1
  - fmt=11.1.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gobject-introspection=1.78.1
  - graphite2=1.3.14
  - graphviz=2.50.0
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=10.2.0
  - icu=73.1
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=8.34.0
  - jedi=0.19.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libarchive=3.7.7
  - libboost=1.82.0
  - libcurl=8.14.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgd=2.3.3
  - libglib=2.78.4
  - libgomp=14.2.0
  - libiconv=1.16
  - libmamba=2.1.0
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - librsvg=2.56.3
  - libsodium=1.0.20
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.7.0
  - libtool=2.4.7
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - mamba=2.1.0
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - ninja=1.12.1
  - ninja-base=1.12.1
  - nlohmann_json=3.11.3
  - nspr=4.35
  - nss=3.89.1
  - openjpeg=2.5.2
  - openssl=3.5.1
  - packaging=24.2
  - pango=1.50.7
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - pixman=0.40.0
  - platformdirs=4.3.6
  - poppler=24.09.0
  - poppler-data=0.4.11
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-graphviz=0.20.1
  - python_abi=3.10
  - pyzmq=26.2.1
  - readline=8.2
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - setuptools=75.8.0
  - simdjson=3.12.3
  - six=1.17.0
  - spdlog=1.15.3
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.0
      - aiohappyeyeballs==2.5.0
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.1.0
      - audioread==3.0.1
      - azure-common==1.1.28
      - azure-core==1.32.0
      - azure-storage-blob==12.24.1
      - babel==2.17.0
      - bcrypt==4.3.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - blobfile==3.0.0
      - blosc2==2.7.1
      - boto3==1.37.9
      - botocore==1.37.9
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - contourpy==1.3.1
      - cryptography==44.0.2
      - cycler==0.12.1
      - datasets==3.3.2
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - dill==0.3.8
      - einops==0.8.1
      - encodec==0.1.1
      - essentia==2.1b6.dev1110
      - et-xmlfile==2.0.0
      - fastjsonschema==2.21.1
      - ffmpeg-python==0.2.0
      - filelock==3.13.1
      - fonttools==4.56.0
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - future==1.0.0
      - gdown==5.2.0
      - google-api-core==2.24.1
      - google-auth==2.38.0
      - google-auth-oauthlib==0.4.6
      - google-cloud-core==2.4.2
      - google-cloud-storage==3.1.0
      - google-crc32c==1.6.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.69.1
      - grpcio==1.72.1
      - h11==0.16.0
      #- h5py==3.6.0
      - hf-transfer==0.1.9
      - hiddenlayer==0.3
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.29.2
      - idna==3.10
      - ipympl==0.9.7
      - ipywidgets==8.1.7
      - isodate==0.7.2
      - isoduration==20.11.0
      - jams==0.3.4
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kagglehub==0.3.12
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      #- librosa==0.8.1
      - llvmlite==0.43.0
      - lxml==5.4.0
      - markdown==3.8
      - markupsafe==2.1.5
      - matplotlib==3.5.1
      #- mido==1.3.3
      - mir-eval==0.8.2
      - mirdata==0.3.9
      - mistune==3.1.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      #- multicoretsne==0.1
      - multidict==6.1.0
      - multiprocess==0.70.16
      - musdb==0.4.3
      #- museval==0.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - ndindex==1.9.2
      - networkx==3.3
      - notebook==7.4.3
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numexpr==2.10.2
      - numpy>=1.23.0
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - openpyxl==3.1.5
      - overrides==7.7.0
      - pandas==1.4.0
      - pandocfilters==1.5.1
      - paramiko==3.5.1
      - pillow==11.0.0
      - pooch==1.8.2
      #- pretty-midi==0.2.10
      - prometheus-client==0.22.1
      - propcache==0.3.0
      - proto-plus==1.26.0
      - protobuf>=3.19.5,<4.0
      - py-cpuinfo==9.0.0
      - pyaml==25.5.0
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pycryptodomex==3.23.0
      - pynacl==1.5.0
      - pyparsing==3.2.1
      - pysocks==1.7.1
      - python-json-logger==3.3.0
      - pytz==2025.1
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - resampy==0.4.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.23.1
      - rsa==4.9
      - s3transfer==0.11.4
      - safetensors==0.5.3
      #- scikit-learn==1.0.2
      - scipy>=1.7.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - simplejson==3.20.1
      - smart-open==7.1.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soundfile>=0.12.1
      - soupsieve==2.7
      - soxr==0.5.0.post1
      - stempeg==0.2.4
      - sympy==1.13.1
      - tables==3.10.1
      - tensorboard==2.8.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tiktoken==0.9.0
      - tinycss2==1.4.0
      - tokenizers==0.21.0
      - tomli==2.2.1
      - torch==2.6.0 #+cu118
      - torchao==0.11.0
      - torchaudio==2.6.0 #+cu118
      - torchcontrib==0.0.2
      - torchdata==0.11.0
      - torchlibrosa==0.0.9
      - torchtune==0.6.1
      - torchvision==0.21.0 #+cu118
      - tqdm==4.67.1
      - transformers==4.50.0 #.dev0
      - triton==3.2.0
      - types-python-dateutil==2.9.0.20250516
      - tzdata==2025.1
      - uri-template==1.3.0
      - urllib3==2.3.0
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - wget==3.2
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yarl==1.18.3
      - zstandard==0.23.0
